// Peer-to-peer Paxos messages. Each message mirrors a struct in
// internal/paxos; internal/wire converts between the two. The Paxos core
// never imports this package.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/paxos/v1/paxos.proto

package paxosv1

import (
	v1 "github.com/Shrutij516/paxos-txn-store/proto/txn/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Ballot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Round         uint64                 `protobuf:"varint,1,opt,name=round,proto3" json:"round,omitempty"`
	Node          int32                  `protobuf:"varint,2,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ballot) Reset() {
	*x = Ballot{}
	mi := &file_proto_paxos_v1_paxos_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ballot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ballot) ProtoMessage() {}

func (x *Ballot) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paxos_v1_paxos_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ballot.ProtoReflect.Descriptor instead.
func (*Ballot) Descriptor() ([]byte, []int) {
	return file_proto_paxos_v1_paxos_proto_rawDescGZIP(), []int{0}
}

func (x *Ballot) GetRound() uint64 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *Ballot) GetNode() int32 {
	if x != nil {
		return x.Node
	}
	return 0
}

type Entry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Noop          bool                   `protobuf:"varint,1,opt,name=noop,proto3" json:"noop,omitempty"`
	ClientId      uint64                 `protobuf:"varint,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Seq           uint64                 `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
	Cmd           []byte                 `protobuf:"bytes,4,opt,name=cmd,proto3" json:"cmd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entry) Reset() {
	*x = Entry{}
	mi := &file_proto_paxos_v1_paxos_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entry) ProtoMessage() {}

func (x *Entry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paxos_v1_paxos_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entry.ProtoReflect.Descriptor instead.
func (*Entry) Descriptor() ([]byte, []int) {
	return file_proto_paxos_v1_paxos_proto_rawDescGZIP(), []int{1}
}

func (x *Entry) GetNoop() bool {
	if x != nil {
		return x.Noop
	}
	return false
}

func (x *Entry) GetClientId() uint64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *Entry) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Entry) GetCmd() []byte {
	if x != nil {
		return x.Cmd
	}
	return nil
}

type SlotEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slot          uint64                 `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`
	Ballot        *Ballot                `protobuf:"bytes,2,opt,name=ballot,proto3" json:"ballot,omitempty"`
	Entry         *Entry                 `protobuf:"bytes,3,opt,name=entry,proto3" json:"entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SlotEntry) Reset() {
	*x = SlotEntry{}
	mi := &file_proto_paxos_v1_paxos_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SlotEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlotEntry) ProtoMessage() {}

func (x *SlotEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paxos_v1_paxos_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlotEntry.ProtoReflect.Descriptor instead.
func (*SlotEntry) Descriptor() ([]byte, []int) {
	return file_proto_paxos_v1_paxos_proto_rawDescGZIP(), []int{2}
}

func (x *SlotEntry) GetSlot() uint64 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *SlotEntry) GetBallot() *Ballot {
	if x != nil {
		return x.Ballot
	}
	return nil
}

func (x *SlotEntry) GetEntry() *Entry {
	if x != nil {
		return x.Entry
	}
	return nil
}

// Single-decree Paxos (internal/paxos Node).
type Prepare struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ballot        *Ballot                `protobuf:"bytes,1,opt,name=ballot,proto3" json:"ballot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Prepare) Reset() {
	*x = Prepare{}
	mi := &file_proto_paxos_v1_paxos_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Prepare) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Prepare) ProtoMessage() {}

func (x *Prepare) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paxos_v1_paxos_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Prepare.ProtoReflect.Descriptor instead.
func (*Prepare) Descriptor() ([]byte, []int) {
	return file_proto_paxos_v1_paxos_proto_rawDescGZIP(), []int{3}
}

func (x *Prepare) GetBallot() *Ballot {
	if x != nil {
		return x.Ballot
	}
	return nil
}

type Promise struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ballot        *Ballot                `protobuf:"bytes,1,opt,name=ballot,proto3" json:"ballot,omitempty"`
	Accepted      *Ballot                `protobuf:"bytes,2,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Value         []byte                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Promise) Reset() {
	*x = Promise{}
	mi := &file_proto_paxos_v1_paxos_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Promise) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Promise) ProtoMessage() {}

func (x *Promise) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paxos_v1_paxos_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Promise.ProtoReflect.Descriptor instead.
func (*Promise) Descriptor() ([]byte, []int) {
	return file_proto_paxos_v1_paxos_proto_rawDescGZIP(), []int{4}
}

func (x *Promise) GetBallot() *Ballot {
	if x != nil {
		return x.Ballot
	}
	return nil
}

func (x *Promise) GetAccepted() *Ballot {
	if x != nil {
		return x.Accepted
	}
	return nil
}

func (x *Promise) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type Accept struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ballot        *Ballot                `protobuf:"bytes,1,opt,name=ballot,proto3" json:"ballot,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Accept) Reset() {
	*x = Accept{}
	mi := &file_proto_paxos_v1_paxos_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Accept) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Accept) ProtoMessage() {}

func (x *Accept) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paxos_v1_paxos_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Accept.ProtoReflect.Descriptor instead.
func (*Accept) Descriptor() ([]byte, []int) {
	return file_proto_paxos_v1_paxos_proto_rawDescGZIP(), []int{5}
}

func (x *Accept) GetBallot() *Ballot {
	if x != nil {
		return x.Ballot
	}
	return nil
}

func (x *Accept) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type Accepted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ballot        *Ballot                `protobuf:"bytes,1,opt,name=ballot,proto3" json:"ballot,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Accepted) Reset() {
	*x = Accepted{}
	mi := &file_proto_paxos_v1_paxos_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Accepted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Accepted) ProtoMessage() {}

func (x *Accepted) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paxos_v1_paxos_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Accepted.ProtoReflect.Descriptor instead.
func (*Accepted) Descriptor() ([]byte, []int) {
	return file_proto_paxos_v1_paxos_proto_rawDescGZIP(), []int{6}
}

func (x *Accepted) GetBallot() *Ballot {
	if x != nil {
		return x.Ballot
	}
	return nil
}

func (x *Accepted) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type Nack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ballot        *Ballot                `protobuf:"bytes,1,opt,name=ballot,proto3" json:"ballot,omitempty"`
	Promised      *Ballot                `protobuf:"bytes,2,opt,name=promised,proto3" json:"promised,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Nack) Reset() {
	*x = Nack{}
	mi := &file_proto_paxos_v1_paxos_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Nack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Nack) ProtoMessage() {}

func (x *Nack) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paxos_v1_paxos_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Nack.ProtoReflect.Descriptor instead.
func (*Nack) Descriptor() ([]byte, []int) {
	return file_proto_paxos_v1_paxos_proto_rawDescGZIP(), []int{7}
}

func (x *Nack) GetBallot() *Ballot {
	if x != nil {
		return x.Ballot
	}
	return nil
}

func (x *Nack) GetPromised() *Ballot {
	if x != nil {
		return x.Promised
	}
	return nil
}

// Multi-Paxos (internal/paxos Replica).
type LogPrepare struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ballot        *Ballot                `protobuf:"bytes,1,opt,name=ballot,proto3" json:"ballot,omitempty"`
	Commit        uint64                 `protobuf:"varint,2,opt,name=commit,proto3" json:"commit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogPrepare) Reset() {
	*x = LogPrepare{}
	mi := &file_proto_paxos_v1_paxos_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogPrepare) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogPrepare) ProtoMessage() {}

func (x *LogPrepare) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paxos_v1_paxos_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogPrepare.ProtoReflect.Descriptor instead.
func (*LogPrepare) Descriptor() ([]byte, []int) {
	return file_proto_paxos_v1_paxos_proto_rawDescGZIP(), []int{8}
}

func (x *LogPrepare) GetBallot() *Ballot {
	if x != nil {
		return x.Ballot
	}
	return nil
}

func (x *LogPrepare) GetCommit() uint64 {
	if x != nil {
		return x.Commit
	}
	return 0
}

type LogPromise struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ballot        *Ballot                `protobuf:"bytes,1,opt,name=ballot,proto3" json:"ballot,omitempty"`
	Entries       []*SlotEntry           `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogPromise) Reset() {
	*x = LogPromise{}
	mi := &file_proto_paxos_v1_paxos_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogPromise) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogPromise) ProtoMessage() {}

func (x *LogPromise) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paxos_v1_paxos_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogPromise.ProtoReflect.Descriptor instead.
func (*LogPromise) Descriptor() ([]byte, []int) {
	return file_proto_paxos_v1_paxos_proto_rawDescGZIP(), []int{9}
}

func (x *LogPromise) GetBallot() *Ballot {
	if x != nil {
		return x.Ballot
	}
	return nil
}

func (x *LogPromise) GetEntries() []*SlotEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type LogAccept struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ballot        *Ballot                `protobuf:"bytes,1,opt,name=ballot,proto3" json:"ballot,omitempty"`
	Slot          uint64                 `protobuf:"varint,2,opt,name=slot,proto3" json:"slot,omitempty"`
	Entry         *Entry                 `protobuf:"bytes,3,opt,name=entry,proto3" json:"entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogAccept) Reset() {
	*x = LogAccept{}
	mi := &file_proto_paxos_v1_paxos_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogAccept) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogAccept) ProtoMessage() {}

func (x *LogAccept) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paxos_v1_paxos_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogAccept.ProtoReflect.Descriptor instead.
func (*LogAccept) Descriptor() ([]byte, []int) {
	return file_proto_paxos_v1_paxos_proto_rawDescGZIP(), []int{10}
}

func (x *LogAccept) GetBallot() *Ballot {
	if x != nil {
		return x.Ballot
	}
	return nil
}

func (x *LogAccept) GetSlot() uint64 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *LogAccept) GetEntry() *Entry {
	if x != nil {
		return x.Entry
	}
	return nil
}

type LogAccepted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ballot        *Ballot                `protobuf:"bytes,1,opt,name=ballot,proto3" json:"ballot,omitempty"`
	Slot          uint64                 `protobuf:"varint,2,opt,name=slot,proto3" json:"slot,omitempty"`
	Entry         *Entry                 `protobuf:"bytes,3,opt,name=entry,proto3" json:"entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogAccepted) Reset() {
	*x = LogAccepted{}
	mi := &file_proto_paxos_v1_paxos_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogAccepted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogAccepted) ProtoMessage() {}

func (x *LogAccepted) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paxos_v1_paxos_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogAccepted.ProtoReflect.Descriptor instead.
func (*LogAccepted) Descriptor() ([]byte, []int) {
	return file_proto_paxos_v1_paxos_proto_rawDescGZIP(), []int{11}
}

func (x *LogAccepted) GetBallot() *Ballot {
	if x != nil {
		return x.Ballot
	}
	return nil
}

func (x *LogAccepted) GetSlot() uint64 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *LogAccepted) GetEntry() *Entry {
	if x != nil {
		return x.Entry
	}
	return nil
}

type LogNack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ballot        *Ballot                `protobuf:"bytes,1,opt,name=ballot,proto3" json:"ballot,omitempty"`
	Promised      *Ballot                `protobuf:"bytes,2,opt,name=promised,proto3" json:"promised,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogNack) Reset() {
	*x = LogNack{}
	mi := &file_proto_paxos_v1_paxos_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogNack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogNack) ProtoMessage() {}

func (x *LogNack) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paxos_v1_paxos_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogNack.ProtoReflect.Descriptor instead.
func (*LogNack) Descriptor() ([]byte, []int) {
	return file_proto_paxos_v1_paxos_proto_rawDescGZIP(), []int{12}
}

func (x *LogNack) GetBallot() *Ballot {
	if x != nil {
		return x.Ballot
	}
	return nil
}

func (x *LogNack) GetPromised() *Ballot {
	if x != nil {
		return x.Promised
	}
	return nil
}

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ballot        *Ballot                `protobuf:"bytes,1,opt,name=ballot,proto3" json:"ballot,omitempty"`
	Commit        uint64                 `protobuf:"varint,2,opt,name=commit,proto3" json:"commit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_proto_paxos_v1_paxos_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paxos_v1_paxos_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_proto_paxos_v1_paxos_proto_rawDescGZIP(), []int{13}
}

func (x *Heartbeat) GetBallot() *Ballot {
	if x != nil {
		return x.Ballot
	}
	return nil
}

func (x *Heartbeat) GetCommit() uint64 {
	if x != nil {
		return x.Commit
	}
	return 0
}

type CatchupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          uint64                 `protobuf:"varint,1,opt,name=from,proto3" json:"from,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CatchupRequest) Reset() {
	*x = CatchupRequest{}
	mi := &file_proto_paxos_v1_paxos_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CatchupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CatchupRequest) ProtoMessage() {}

func (x *CatchupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paxos_v1_paxos_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CatchupRequest.ProtoReflect.Descriptor instead.
func (*CatchupRequest) Descriptor() ([]byte, []int) {
	return file_proto_paxos_v1_paxos_proto_rawDescGZIP(), []int{14}
}

func (x *CatchupRequest) GetFrom() uint64 {
	if x != nil {
		return x.From
	}
	return 0
}

type CatchupReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*SlotEntry           `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CatchupReply) Reset() {
	*x = CatchupReply{}
	mi := &file_proto_paxos_v1_paxos_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CatchupReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CatchupReply) ProtoMessage() {}

func (x *CatchupReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paxos_v1_paxos_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CatchupReply.ProtoReflect.Descriptor instead.
func (*CatchupReply) Descriptor() ([]byte, []int) {
	return file_proto_paxos_v1_paxos_proto_rawDescGZIP(), []int{15}
}

func (x *CatchupReply) GetEntries() []*SlotEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type ClientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      uint64                 `protobuf:"varint,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Seq           uint64                 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	Cmd           []byte                 `protobuf:"bytes,3,opt,name=cmd,proto3" json:"cmd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientRequest) Reset() {
	*x = ClientRequest{}
	mi := &file_proto_paxos_v1_paxos_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientRequest) ProtoMessage() {}

func (x *ClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paxos_v1_paxos_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientRequest.ProtoReflect.Descriptor instead.
func (*ClientRequest) Descriptor() ([]byte, []int) {
	return file_proto_paxos_v1_paxos_proto_rawDescGZIP(), []int{16}
}

func (x *ClientRequest) GetClientId() uint64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *ClientRequest) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *ClientRequest) GetCmd() []byte {
	if x != nil {
		return x.Cmd
	}
	return nil
}

type ClientReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      uint64                 `protobuf:"varint,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Seq           uint64                 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	Ok            bool                   `protobuf:"varint,3,opt,name=ok,proto3" json:"ok,omitempty"`
	Result        []byte                 `protobuf:"bytes,4,opt,name=result,proto3" json:"result,omitempty"`
	Leader        int32                  `protobuf:"varint,5,opt,name=leader,proto3" json:"leader,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientReply) Reset() {
	*x = ClientReply{}
	mi := &file_proto_paxos_v1_paxos_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientReply) ProtoMessage() {}

func (x *ClientReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paxos_v1_paxos_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientReply.ProtoReflect.Descriptor instead.
func (*ClientReply) Descriptor() ([]byte, []int) {
	return file_proto_paxos_v1_paxos_proto_rawDescGZIP(), []int{17}
}

func (x *ClientReply) GetClientId() uint64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *ClientReply) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *ClientReply) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ClientReply) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ClientReply) GetLeader() int32 {
	if x != nil {
		return x.Leader
	}
	return 0
}

// Envelope carries exactly one message between two nodes. A node hosts
// one replica of every shard; shard names the replica group the message
// belongs to (sender and receiver are replicas of the same shard, except
// for two-phase commit messages, which go to the receiving shard).
type Envelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	From  int32                  `protobuf:"varint,1,opt,name=from,proto3" json:"from,omitempty"`
	To    int32                  `protobuf:"varint,2,opt,name=to,proto3" json:"to,omitempty"`
	Shard uint32                 `protobuf:"varint,3,opt,name=shard,proto3" json:"shard,omitempty"`
	// W3C trace context (traceparent, tracestate) of the transaction a
	// two-phase commit message belongs to, so one transaction is one trace
	// across shards and nodes. Empty for Paxos messages.
	Trace map[string]string `protobuf:"bytes,4,rep,name=trace,proto3" json:"trace,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Types that are valid to be assigned to Body:
	//
	//	*Envelope_Prepare
	//	*Envelope_Promise
	//	*Envelope_Accept
	//	*Envelope_Accepted
	//	*Envelope_Nack
	//	*Envelope_LogPrepare
	//	*Envelope_LogPromise
	//	*Envelope_LogAccept
	//	*Envelope_LogAccepted
	//	*Envelope_LogNack
	//	*Envelope_Heartbeat
	//	*Envelope_CatchupRequest
	//	*Envelope_CatchupReply
	//	*Envelope_ClientRequest
	//	*Envelope_ClientReply
	//	*Envelope_PrepareReq
	//	*Envelope_Vote
	//	*Envelope_Decision
	//	*Envelope_QueryOutcome
	//	*Envelope_WoundReq
	Body          isEnvelope_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_proto_paxos_v1_paxos_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paxos_v1_paxos_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_proto_paxos_v1_paxos_proto_rawDescGZIP(), []int{18}
}

func (x *Envelope) GetFrom() int32 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *Envelope) GetTo() int32 {
	if x != nil {
		return x.To
	}
	return 0
}

func (x *Envelope) GetShard() uint32 {
	if x != nil {
		return x.Shard
	}
	return 0
}

func (x *Envelope) GetTrace() map[string]string {
	if x != nil {
		return x.Trace
	}
	return nil
}

func (x *Envelope) GetBody() isEnvelope_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Envelope) GetPrepare() *Prepare {
	if x != nil {
		if x, ok := x.Body.(*Envelope_Prepare); ok {
			return x.Prepare
		}
	}
	return nil
}

func (x *Envelope) GetPromise() *Promise {
	if x != nil {
		if x, ok := x.Body.(*Envelope_Promise); ok {
			return x.Promise
		}
	}
	return nil
}

func (x *Envelope) GetAccept() *Accept {
	if x != nil {
		if x, ok := x.Body.(*Envelope_Accept); ok {
			return x.Accept
		}
	}
	return nil
}

func (x *Envelope) GetAccepted() *Accepted {
	if x != nil {
		if x, ok := x.Body.(*Envelope_Accepted); ok {
			return x.Accepted
		}
	}
	return nil
}

func (x *Envelope) GetNack() *Nack {
	if x != nil {
		if x, ok := x.Body.(*Envelope_Nack); ok {
			return x.Nack
		}
	}
	return nil
}

func (x *Envelope) GetLogPrepare() *LogPrepare {
	if x != nil {
		if x, ok := x.Body.(*Envelope_LogPrepare); ok {
			return x.LogPrepare
		}
	}
	return nil
}

func (x *Envelope) GetLogPromise() *LogPromise {
	if x != nil {
		if x, ok := x.Body.(*Envelope_LogPromise); ok {
			return x.LogPromise
		}
	}
	return nil
}

func (x *Envelope) GetLogAccept() *LogAccept {
	if x != nil {
		if x, ok := x.Body.(*Envelope_LogAccept); ok {
			return x.LogAccept
		}
	}
	return nil
}

func (x *Envelope) GetLogAccepted() *LogAccepted {
	if x != nil {
		if x, ok := x.Body.(*Envelope_LogAccepted); ok {
			return x.LogAccepted
		}
	}
	return nil
}

func (x *Envelope) GetLogNack() *LogNack {
	if x != nil {
		if x, ok := x.Body.(*Envelope_LogNack); ok {
			return x.LogNack
		}
	}
	return nil
}

func (x *Envelope) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Body.(*Envelope_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *Envelope) GetCatchupRequest() *CatchupRequest {
	if x != nil {
		if x, ok := x.Body.(*Envelope_CatchupRequest); ok {
			return x.CatchupRequest
		}
	}
	return nil
}

func (x *Envelope) GetCatchupReply() *CatchupReply {
	if x != nil {
		if x, ok := x.Body.(*Envelope_CatchupReply); ok {
			return x.CatchupReply
		}
	}
	return nil
}

func (x *Envelope) GetClientRequest() *ClientRequest {
	if x != nil {
		if x, ok := x.Body.(*Envelope_ClientRequest); ok {
			return x.ClientRequest
		}
	}
	return nil
}

func (x *Envelope) GetClientReply() *ClientReply {
	if x != nil {
		if x, ok := x.Body.(*Envelope_ClientReply); ok {
			return x.ClientReply
		}
	}
	return nil
}

func (x *Envelope) GetPrepareReq() *v1.PrepareReq {
	if x != nil {
		if x, ok := x.Body.(*Envelope_PrepareReq); ok {
			return x.PrepareReq
		}
	}
	return nil
}

func (x *Envelope) GetVote() *v1.Vote {
	if x != nil {
		if x, ok := x.Body.(*Envelope_Vote); ok {
			return x.Vote
		}
	}
	return nil
}

func (x *Envelope) GetDecision() *v1.Decision {
	if x != nil {
		if x, ok := x.Body.(*Envelope_Decision); ok {
			return x.Decision
		}
	}
	return nil
}

func (x *Envelope) GetQueryOutcome() *v1.QueryOutcome {
	if x != nil {
		if x, ok := x.Body.(*Envelope_QueryOutcome); ok {
			return x.QueryOutcome
		}
	}
	return nil
}

func (x *Envelope) GetWoundReq() *v1.WoundReq {
	if x != nil {
		if x, ok := x.Body.(*Envelope_WoundReq); ok {
			return x.WoundReq
		}
	}
	return nil
}

type isEnvelope_Body interface {
	isEnvelope_Body()
}

type Envelope_Prepare struct {
	Prepare *Prepare `protobuf:"bytes,10,opt,name=prepare,proto3,oneof"`
}

type Envelope_Promise struct {
	Promise *Promise `protobuf:"bytes,11,opt,name=promise,proto3,oneof"`
}

type Envelope_Accept struct {
	Accept *Accept `protobuf:"bytes,12,opt,name=accept,proto3,oneof"`
}

type Envelope_Accepted struct {
	Accepted *Accepted `protobuf:"bytes,13,opt,name=accepted,proto3,oneof"`
}

type Envelope_Nack struct {
	Nack *Nack `protobuf:"bytes,14,opt,name=nack,proto3,oneof"`
}

type Envelope_LogPrepare struct {
	LogPrepare *LogPrepare `protobuf:"bytes,20,opt,name=log_prepare,json=logPrepare,proto3,oneof"`
}

type Envelope_LogPromise struct {
	LogPromise *LogPromise `protobuf:"bytes,21,opt,name=log_promise,json=logPromise,proto3,oneof"`
}

type Envelope_LogAccept struct {
	LogAccept *LogAccept `protobuf:"bytes,22,opt,name=log_accept,json=logAccept,proto3,oneof"`
}

type Envelope_LogAccepted struct {
	LogAccepted *LogAccepted `protobuf:"bytes,23,opt,name=log_accepted,json=logAccepted,proto3,oneof"`
}

type Envelope_LogNack struct {
	LogNack *LogNack `protobuf:"bytes,24,opt,name=log_nack,json=logNack,proto3,oneof"`
}

type Envelope_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,25,opt,name=heartbeat,proto3,oneof"`
}

type Envelope_CatchupRequest struct {
	CatchupRequest *CatchupRequest `protobuf:"bytes,26,opt,name=catchup_request,json=catchupRequest,proto3,oneof"`
}

type Envelope_CatchupReply struct {
	CatchupReply *CatchupReply `protobuf:"bytes,27,opt,name=catchup_reply,json=catchupReply,proto3,oneof"`
}

type Envelope_ClientRequest struct {
	ClientRequest *ClientRequest `protobuf:"bytes,28,opt,name=client_request,json=clientRequest,proto3,oneof"`
}

type Envelope_ClientReply struct {
	ClientReply *ClientReply `protobuf:"bytes,29,opt,name=client_reply,json=clientReply,proto3,oneof"`
}

type Envelope_PrepareReq struct {
	PrepareReq *v1.PrepareReq `protobuf:"bytes,30,opt,name=prepare_req,json=prepareReq,proto3,oneof"`
}

type Envelope_Vote struct {
	Vote *v1.Vote `protobuf:"bytes,31,opt,name=vote,proto3,oneof"`
}

type Envelope_Decision struct {
	Decision *v1.Decision `protobuf:"bytes,32,opt,name=decision,proto3,oneof"`
}

type Envelope_QueryOutcome struct {
	QueryOutcome *v1.QueryOutcome `protobuf:"bytes,33,opt,name=query_outcome,json=queryOutcome,proto3,oneof"`
}

type Envelope_WoundReq struct {
	WoundReq *v1.WoundReq `protobuf:"bytes,34,opt,name=wound_req,json=woundReq,proto3,oneof"`
}

func (*Envelope_Prepare) isEnvelope_Body() {}

func (*Envelope_Promise) isEnvelope_Body() {}

func (*Envelope_Accept) isEnvelope_Body() {}

func (*Envelope_Accepted) isEnvelope_Body() {}

func (*Envelope_Nack) isEnvelope_Body() {}

func (*Envelope_LogPrepare) isEnvelope_Body() {}

func (*Envelope_LogPromise) isEnvelope_Body() {}

func (*Envelope_LogAccept) isEnvelope_Body() {}

func (*Envelope_LogAccepted) isEnvelope_Body() {}

func (*Envelope_LogNack) isEnvelope_Body() {}

func (*Envelope_Heartbeat) isEnvelope_Body() {}

func (*Envelope_CatchupRequest) isEnvelope_Body() {}

func (*Envelope_CatchupReply) isEnvelope_Body() {}

func (*Envelope_ClientRequest) isEnvelope_Body() {}

func (*Envelope_ClientReply) isEnvelope_Body() {}

func (*Envelope_PrepareReq) isEnvelope_Body() {}

func (*Envelope_Vote) isEnvelope_Body() {}

func (*Envelope_Decision) isEnvelope_Body() {}

func (*Envelope_QueryOutcome) isEnvelope_Body() {}

func (*Envelope_WoundReq) isEnvelope_Body() {}

type SendAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendAck) Reset() {
	*x = SendAck{}
	mi := &file_proto_paxos_v1_paxos_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendAck) ProtoMessage() {}

func (x *SendAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paxos_v1_paxos_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendAck.ProtoReflect.Descriptor instead.
func (*SendAck) Descriptor() ([]byte, []int) {
	return file_proto_paxos_v1_paxos_proto_rawDescGZIP(), []int{19}
}

var File_proto_paxos_v1_paxos_proto protoreflect.FileDescriptor

const file_proto_paxos_v1_paxos_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/paxos/v1/paxos.proto\x12\bpaxos.v1\x1a\x16proto/txn/v1/txn.proto\"2\n" +
	"\x06Ballot\x12\x14\n" +
	"\x05round\x18\x01 \x01(\x04R\x05round\x12\x12\n" +
	"\x04node\x18\x02 \x01(\x05R\x04node\"\\\n" +
	"\x05Entry\x12\x12\n" +
	"\x04noop\x18\x01 \x01(\bR\x04noop\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\x04R\bclientId\x12\x10\n" +
	"\x03seq\x18\x03 \x01(\x04R\x03seq\x12\x10\n" +
	"\x03cmd\x18\x04 \x01(\fR\x03cmd\"p\n" +
	"\tSlotEntry\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\x04R\x04slot\x12(\n" +
	"\x06ballot\x18\x02 \x01(\v2\x10.paxos.v1.BallotR\x06ballot\x12%\n" +
	"\x05entry\x18\x03 \x01(\v2\x0f.paxos.v1.EntryR\x05entry\"3\n" +
	"\aPrepare\x12(\n" +
	"\x06ballot\x18\x01 \x01(\v2\x10.paxos.v1.BallotR\x06ballot\"w\n" +
	"\aPromise\x12(\n" +
	"\x06ballot\x18\x01 \x01(\v2\x10.paxos.v1.BallotR\x06ballot\x12,\n" +
	"\baccepted\x18\x02 \x01(\v2\x10.paxos.v1.BallotR\baccepted\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value\"H\n" +
	"\x06Accept\x12(\n" +
	"\x06ballot\x18\x01 \x01(\v2\x10.paxos.v1.BallotR\x06ballot\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"J\n" +
	"\bAccepted\x12(\n" +
	"\x06ballot\x18\x01 \x01(\v2\x10.paxos.v1.BallotR\x06ballot\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"^\n" +
	"\x04Nack\x12(\n" +
	"\x06ballot\x18\x01 \x01(\v2\x10.paxos.v1.BallotR\x06ballot\x12,\n" +
	"\bpromised\x18\x02 \x01(\v2\x10.paxos.v1.BallotR\bpromised\"N\n" +
	"\n" +
	"LogPrepare\x12(\n" +
	"\x06ballot\x18\x01 \x01(\v2\x10.paxos.v1.BallotR\x06ballot\x12\x16\n" +
	"\x06commit\x18\x02 \x01(\x04R\x06commit\"e\n" +
	"\n" +
	"LogPromise\x12(\n" +
	"\x06ballot\x18\x01 \x01(\v2\x10.paxos.v1.BallotR\x06ballot\x12-\n" +
	"\aentries\x18\x02 \x03(\v2\x13.paxos.v1.SlotEntryR\aentries\"p\n" +
	"\tLogAccept\x12(\n" +
	"\x06ballot\x18\x01 \x01(\v2\x10.paxos.v1.BallotR\x06ballot\x12\x12\n" +
	"\x04slot\x18\x02 \x01(\x04R\x04slot\x12%\n" +
	"\x05entry\x18\x03 \x01(\v2\x0f.paxos.v1.EntryR\x05entry\"r\n" +
	"\vLogAccepted\x12(\n" +
	"\x06ballot\x18\x01 \x01(\v2\x10.paxos.v1.BallotR\x06ballot\x12\x12\n" +
	"\x04slot\x18\x02 \x01(\x04R\x04slot\x12%\n" +
	"\x05entry\x18\x03 \x01(\v2\x0f.paxos.v1.EntryR\x05entry\"a\n" +
	"\aLogNack\x12(\n" +
	"\x06ballot\x18\x01 \x01(\v2\x10.paxos.v1.BallotR\x06ballot\x12,\n" +
	"\bpromised\x18\x02 \x01(\v2\x10.paxos.v1.BallotR\bpromised\"M\n" +
	"\tHeartbeat\x12(\n" +
	"\x06ballot\x18\x01 \x01(\v2\x10.paxos.v1.BallotR\x06ballot\x12\x16\n" +
	"\x06commit\x18\x02 \x01(\x04R\x06commit\"$\n" +
	"\x0eCatchupRequest\x12\x12\n" +
	"\x04from\x18\x01 \x01(\x04R\x04from\"=\n" +
	"\fCatchupReply\x12-\n" +
	"\aentries\x18\x01 \x03(\v2\x13.paxos.v1.SlotEntryR\aentries\"P\n" +
	"\rClientRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\x04R\bclientId\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x04R\x03seq\x12\x10\n" +
	"\x03cmd\x18\x03 \x01(\fR\x03cmd\"|\n" +
	"\vClientReply\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\x04R\bclientId\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x04R\x03seq\x12\x0e\n" +
	"\x02ok\x18\x03 \x01(\bR\x02ok\x12\x16\n" +
	"\x06result\x18\x04 \x01(\fR\x06result\x12\x16\n" +
	"\x06leader\x18\x05 \x01(\x05R\x06leader\"\xe1\t\n" +
	"\bEnvelope\x12\x12\n" +
	"\x04from\x18\x01 \x01(\x05R\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\x05R\x02to\x12\x14\n" +
	"\x05shard\x18\x03 \x01(\rR\x05shard\x123\n" +
	"\x05trace\x18\x04 \x03(\v2\x1d.paxos.v1.Envelope.TraceEntryR\x05trace\x12-\n" +
	"\aprepare\x18\n" +
	" \x01(\v2\x11.paxos.v1.PrepareH\x00R\aprepare\x12-\n" +
	"\apromise\x18\v \x01(\v2\x11.paxos.v1.PromiseH\x00R\apromise\x12*\n" +
	"\x06accept\x18\f \x01(\v2\x10.paxos.v1.AcceptH\x00R\x06accept\x120\n" +
	"\baccepted\x18\r \x01(\v2\x12.paxos.v1.AcceptedH\x00R\baccepted\x12$\n" +
	"\x04nack\x18\x0e \x01(\v2\x0e.paxos.v1.NackH\x00R\x04nack\x127\n" +
	"\vlog_prepare\x18\x14 \x01(\v2\x14.paxos.v1.LogPrepareH\x00R\n" +
	"logPrepare\x127\n" +
	"\vlog_promise\x18\x15 \x01(\v2\x14.paxos.v1.LogPromiseH\x00R\n" +
	"logPromise\x124\n" +
	"\n" +
	"log_accept\x18\x16 \x01(\v2\x13.paxos.v1.LogAcceptH\x00R\tlogAccept\x12:\n" +
	"\flog_accepted\x18\x17 \x01(\v2\x15.paxos.v1.LogAcceptedH\x00R\vlogAccepted\x12.\n" +
	"\blog_nack\x18\x18 \x01(\v2\x11.paxos.v1.LogNackH\x00R\alogNack\x123\n" +
	"\theartbeat\x18\x19 \x01(\v2\x13.paxos.v1.HeartbeatH\x00R\theartbeat\x12C\n" +
	"\x0fcatchup_request\x18\x1a \x01(\v2\x18.paxos.v1.CatchupRequestH\x00R\x0ecatchupRequest\x12=\n" +
	"\rcatchup_reply\x18\x1b \x01(\v2\x16.paxos.v1.CatchupReplyH\x00R\fcatchupReply\x12@\n" +
	"\x0eclient_request\x18\x1c \x01(\v2\x17.paxos.v1.ClientRequestH\x00R\rclientRequest\x12:\n" +
	"\fclient_reply\x18\x1d \x01(\v2\x15.paxos.v1.ClientReplyH\x00R\vclientReply\x125\n" +
	"\vprepare_req\x18\x1e \x01(\v2\x12.txn.v1.PrepareReqH\x00R\n" +
	"prepareReq\x12\"\n" +
	"\x04vote\x18\x1f \x01(\v2\f.txn.v1.VoteH\x00R\x04vote\x12.\n" +
	"\bdecision\x18  \x01(\v2\x10.txn.v1.DecisionH\x00R\bdecision\x12;\n" +
	"\rquery_outcome\x18! \x01(\v2\x14.txn.v1.QueryOutcomeH\x00R\fqueryOutcome\x12/\n" +
	"\twound_req\x18\" \x01(\v2\x10.txn.v1.WoundReqH\x00R\bwoundReq\x1a8\n" +
	"\n" +
	"TraceEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x06\n" +
	"\x04body\"\t\n" +
	"\aSendAck25\n" +
	"\x04Peer\x12-\n" +
	"\x04Send\x12\x12.paxos.v1.Envelope\x1a\x11.paxos.v1.SendAckB>Z<github.com/Shrutij516/paxos-txn-store/proto/paxos/v1;paxosv1b\x06proto3"

var (
	file_proto_paxos_v1_paxos_proto_rawDescOnce sync.Once
	file_proto_paxos_v1_paxos_proto_rawDescData []byte
)

func file_proto_paxos_v1_paxos_proto_rawDescGZIP() []byte {
	file_proto_paxos_v1_paxos_proto_rawDescOnce.Do(func() {
		file_proto_paxos_v1_paxos_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_paxos_v1_paxos_proto_rawDesc), len(file_proto_paxos_v1_paxos_proto_rawDesc)))
	})
	return file_proto_paxos_v1_paxos_proto_rawDescData
}

var file_proto_paxos_v1_paxos_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_proto_paxos_v1_paxos_proto_goTypes = []any{
	(*Ballot)(nil),          // 0: paxos.v1.Ballot
	(*Entry)(nil),           // 1: paxos.v1.Entry
	(*SlotEntry)(nil),       // 2: paxos.v1.SlotEntry
	(*Prepare)(nil),         // 3: paxos.v1.Prepare
	(*Promise)(nil),         // 4: paxos.v1.Promise
	(*Accept)(nil),          // 5: paxos.v1.Accept
	(*Accepted)(nil),        // 6: paxos.v1.Accepted
	(*Nack)(nil),            // 7: paxos.v1.Nack
	(*LogPrepare)(nil),      // 8: paxos.v1.LogPrepare
	(*LogPromise)(nil),      // 9: paxos.v1.LogPromise
	(*LogAccept)(nil),       // 10: paxos.v1.LogAccept
	(*LogAccepted)(nil),     // 11: paxos.v1.LogAccepted
	(*LogNack)(nil),         // 12: paxos.v1.LogNack
	(*Heartbeat)(nil),       // 13: paxos.v1.Heartbeat
	(*CatchupRequest)(nil),  // 14: paxos.v1.CatchupRequest
	(*CatchupReply)(nil),    // 15: paxos.v1.CatchupReply
	(*ClientRequest)(nil),   // 16: paxos.v1.ClientRequest
	(*ClientReply)(nil),     // 17: paxos.v1.ClientReply
	(*Envelope)(nil),        // 18: paxos.v1.Envelope
	(*SendAck)(nil),         // 19: paxos.v1.SendAck
	nil,                     // 20: paxos.v1.Envelope.TraceEntry
	(*v1.PrepareReq)(nil),   // 21: txn.v1.PrepareReq
	(*v1.Vote)(nil),         // 22: txn.v1.Vote
	(*v1.Decision)(nil),     // 23: txn.v1.Decision
	(*v1.QueryOutcome)(nil), // 24: txn.v1.QueryOutcome
	(*v1.WoundReq)(nil),     // 25: txn.v1.WoundReq
}
var file_proto_paxos_v1_paxos_proto_depIdxs = []int32{
	0,  // 0: paxos.v1.SlotEntry.ballot:type_name -> paxos.v1.Ballot
	1,  // 1: paxos.v1.SlotEntry.entry:type_name -> paxos.v1.Entry
	0,  // 2: paxos.v1.Prepare.ballot:type_name -> paxos.v1.Ballot
	0,  // 3: paxos.v1.Promise.ballot:type_name -> paxos.v1.Ballot
	0,  // 4: paxos.v1.Promise.accepted:type_name -> paxos.v1.Ballot
	0,  // 5: paxos.v1.Accept.ballot:type_name -> paxos.v1.Ballot
	0,  // 6: paxos.v1.Accepted.ballot:type_name -> paxos.v1.Ballot
	0,  // 7: paxos.v1.Nack.ballot:type_name -> paxos.v1.Ballot
	0,  // 8: paxos.v1.Nack.promised:type_name -> paxos.v1.Ballot
	0,  // 9: paxos.v1.LogPrepare.ballot:type_name -> paxos.v1.Ballot
	0,  // 10: paxos.v1.LogPromise.ballot:type_name -> paxos.v1.Ballot
	2,  // 11: paxos.v1.LogPromise.entries:type_name -> paxos.v1.SlotEntry
	0,  // 12: paxos.v1.LogAccept.ballot:type_name -> paxos.v1.Ballot
	1,  // 13: paxos.v1.LogAccept.entry:type_name -> paxos.v1.Entry
	0,  // 14: paxos.v1.LogAccepted.ballot:type_name -> paxos.v1.Ballot
	1,  // 15: paxos.v1.LogAccepted.entry:type_name -> paxos.v1.Entry
	0,  // 16: paxos.v1.LogNack.ballot:type_name -> paxos.v1.Ballot
	0,  // 17: paxos.v1.LogNack.promised:type_name -> paxos.v1.Ballot
	0,  // 18: paxos.v1.Heartbeat.ballot:type_name -> paxos.v1.Ballot
	2,  // 19: paxos.v1.CatchupReply.entries:type_name -> paxos.v1.SlotEntry
	20, // 20: paxos.v1.Envelope.trace:type_name -> paxos.v1.Envelope.TraceEntry
	3,  // 21: paxos.v1.Envelope.prepare:type_name -> paxos.v1.Prepare
	4,  // 22: paxos.v1.Envelope.promise:type_name -> paxos.v1.Promise
	5,  // 23: paxos.v1.Envelope.accept:type_name -> paxos.v1.Accept
	6,  // 24: paxos.v1.Envelope.accepted:type_name -> paxos.v1.Accepted
	7,  // 25: paxos.v1.Envelope.nack:type_name -> paxos.v1.Nack
	8,  // 26: paxos.v1.Envelope.log_prepare:type_name -> paxos.v1.LogPrepare
	9,  // 27: paxos.v1.Envelope.log_promise:type_name -> paxos.v1.LogPromise
	10, // 28: paxos.v1.Envelope.log_accept:type_name -> paxos.v1.LogAccept
	11, // 29: paxos.v1.Envelope.log_accepted:type_name -> paxos.v1.LogAccepted
	12, // 30: paxos.v1.Envelope.log_nack:type_name -> paxos.v1.LogNack
	13, // 31: paxos.v1.Envelope.heartbeat:type_name -> paxos.v1.Heartbeat
	14, // 32: paxos.v1.Envelope.catchup_request:type_name -> paxos.v1.CatchupRequest
	15, // 33: paxos.v1.Envelope.catchup_reply:type_name -> paxos.v1.CatchupReply
	16, // 34: paxos.v1.Envelope.client_request:type_name -> paxos.v1.ClientRequest
	17, // 35: paxos.v1.Envelope.client_reply:type_name -> paxos.v1.ClientReply
	21, // 36: paxos.v1.Envelope.prepare_req:type_name -> txn.v1.PrepareReq
	22, // 37: paxos.v1.Envelope.vote:type_name -> txn.v1.Vote
	23, // 38: paxos.v1.Envelope.decision:type_name -> txn.v1.Decision
	24, // 39: paxos.v1.Envelope.query_outcome:type_name -> txn.v1.QueryOutcome
	25, // 40: paxos.v1.Envelope.wound_req:type_name -> txn.v1.WoundReq
	18, // 41: paxos.v1.Peer.Send:input_type -> paxos.v1.Envelope
	19, // 42: paxos.v1.Peer.Send:output_type -> paxos.v1.SendAck
	42, // [42:43] is the sub-list for method output_type
	41, // [41:42] is the sub-list for method input_type
	41, // [41:41] is the sub-list for extension type_name
	41, // [41:41] is the sub-list for extension extendee
	0,  // [0:41] is the sub-list for field type_name
}

func init() { file_proto_paxos_v1_paxos_proto_init() }
func file_proto_paxos_v1_paxos_proto_init() {
	if File_proto_paxos_v1_paxos_proto != nil {
		return
	}
	file_proto_paxos_v1_paxos_proto_msgTypes[18].OneofWrappers = []any{
		(*Envelope_Prepare)(nil),
		(*Envelope_Promise)(nil),
		(*Envelope_Accept)(nil),
		(*Envelope_Accepted)(nil),
		(*Envelope_Nack)(nil),
		(*Envelope_LogPrepare)(nil),
		(*Envelope_LogPromise)(nil),
		(*Envelope_LogAccept)(nil),
		(*Envelope_LogAccepted)(nil),
		(*Envelope_LogNack)(nil),
		(*Envelope_Heartbeat)(nil),
		(*Envelope_CatchupRequest)(nil),
		(*Envelope_CatchupReply)(nil),
		(*Envelope_ClientRequest)(nil),
		(*Envelope_ClientReply)(nil),
		(*Envelope_PrepareReq)(nil),
		(*Envelope_Vote)(nil),
		(*Envelope_Decision)(nil),
		(*Envelope_QueryOutcome)(nil),
		(*Envelope_WoundReq)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_paxos_v1_paxos_proto_rawDesc), len(file_proto_paxos_v1_paxos_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_paxos_v1_paxos_proto_goTypes,
		DependencyIndexes: file_proto_paxos_v1_paxos_proto_depIdxs,
		MessageInfos:      file_proto_paxos_v1_paxos_proto_msgTypes,
	}.Build()
	File_proto_paxos_v1_paxos_proto = out.File
	file_proto_paxos_v1_paxos_proto_goTypes = nil
	file_proto_paxos_v1_paxos_proto_depIdxs = nil
}
