// Sharded transactions. The Txn service is the client API; the messages
// under "Two-phase commit" travel between nodes inside the peer service's
// Envelope (proto/paxos/v1). internal/wire converts those to and from the
// structs in internal/txn.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.29.3
// source: proto/txn/v1/txn.proto

package txnv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_STATUS_UNSPECIFIED Status = 0
	// Done. For Commit: the transaction committed.
	Status_STATUS_OK Status = 1
	// The transaction was aborted (wounded, a lock or read became stale, or
	// the commit decision was abort). Start a new attempt.
	Status_STATUS_ABORTED Status = 2
	// This node does not lead the shard; leader names the one it knows of.
	Status_STATUS_NOT_LEADER Status = 3
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_OK",
		2: "STATUS_ABORTED",
		3: "STATUS_NOT_LEADER",
	}
	Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"STATUS_OK":          1,
		"STATUS_ABORTED":     2,
		"STATUS_NOT_LEADER":  3,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_txn_v1_txn_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_proto_txn_v1_txn_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_proto_txn_v1_txn_proto_rawDescGZIP(), []int{0}
}

// TxnMeta identifies one attempt of a transaction. ts is its start
// timestamp for wound-wait (smaller is older); a retry keeps it.
type TxnMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Ts            uint64                 `protobuf:"varint,2,opt,name=ts,proto3" json:"ts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxnMeta) Reset() {
	*x = TxnMeta{}
	mi := &file_proto_txn_v1_txn_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxnMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxnMeta) ProtoMessage() {}

func (x *TxnMeta) ProtoReflect() protoreflect.Message {
	mi := &file_proto_txn_v1_txn_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxnMeta.ProtoReflect.Descriptor instead.
func (*TxnMeta) Descriptor() ([]byte, []int) {
	return file_proto_txn_v1_txn_proto_rawDescGZIP(), []int{0}
}

func (x *TxnMeta) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TxnMeta) GetTs() uint64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

// Part is one shard's share of a transaction: the versions it read and
// the values it writes.
type Part struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shard         uint32                 `protobuf:"varint,1,opt,name=shard,proto3" json:"shard,omitempty"`
	Reads         map[string]uint64      `protobuf:"bytes,2,rep,name=reads,proto3" json:"reads,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Writes        map[string]string      `protobuf:"bytes,3,rep,name=writes,proto3" json:"writes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Part) Reset() {
	*x = Part{}
	mi := &file_proto_txn_v1_txn_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Part) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Part) ProtoMessage() {}

func (x *Part) ProtoReflect() protoreflect.Message {
	mi := &file_proto_txn_v1_txn_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Part.ProtoReflect.Descriptor instead.
func (*Part) Descriptor() ([]byte, []int) {
	return file_proto_txn_v1_txn_proto_rawDescGZIP(), []int{1}
}

func (x *Part) GetShard() uint32 {
	if x != nil {
		return x.Shard
	}
	return 0
}

func (x *Part) GetReads() map[string]uint64 {
	if x != nil {
		return x.Reads
	}
	return nil
}

func (x *Part) GetWrites() map[string]string {
	if x != nil {
		return x.Writes
	}
	return nil
}

type PrepareReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Txn           *TxnMeta               `protobuf:"bytes,1,opt,name=txn,proto3" json:"txn,omitempty"`
	Coord         uint32                 `protobuf:"varint,2,opt,name=coord,proto3" json:"coord,omitempty"`
	Participants  []uint32               `protobuf:"varint,3,rep,packed,name=participants,proto3" json:"participants,omitempty"`
	Part          *Part                  `protobuf:"bytes,4,opt,name=part,proto3" json:"part,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareReq) Reset() {
	*x = PrepareReq{}
	mi := &file_proto_txn_v1_txn_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareReq) ProtoMessage() {}

func (x *PrepareReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_txn_v1_txn_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareReq.ProtoReflect.Descriptor instead.
func (*PrepareReq) Descriptor() ([]byte, []int) {
	return file_proto_txn_v1_txn_proto_rawDescGZIP(), []int{2}
}

func (x *PrepareReq) GetTxn() *TxnMeta {
	if x != nil {
		return x.Txn
	}
	return nil
}

func (x *PrepareReq) GetCoord() uint32 {
	if x != nil {
		return x.Coord
	}
	return 0
}

func (x *PrepareReq) GetParticipants() []uint32 {
	if x != nil {
		return x.Participants
	}
	return nil
}

func (x *PrepareReq) GetPart() *Part {
	if x != nil {
		return x.Part
	}
	return nil
}

type Vote struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Txn           uint64                 `protobuf:"varint,1,opt,name=txn,proto3" json:"txn,omitempty"`
	Shard         uint32                 `protobuf:"varint,2,opt,name=shard,proto3" json:"shard,omitempty"`
	Yes           bool                   `protobuf:"varint,3,opt,name=yes,proto3" json:"yes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vote) Reset() {
	*x = Vote{}
	mi := &file_proto_txn_v1_txn_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vote) ProtoMessage() {}

func (x *Vote) ProtoReflect() protoreflect.Message {
	mi := &file_proto_txn_v1_txn_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vote.ProtoReflect.Descriptor instead.
func (*Vote) Descriptor() ([]byte, []int) {
	return file_proto_txn_v1_txn_proto_rawDescGZIP(), []int{3}
}

func (x *Vote) GetTxn() uint64 {
	if x != nil {
		return x.Txn
	}
	return 0
}

func (x *Vote) GetShard() uint32 {
	if x != nil {
		return x.Shard
	}
	return 0
}

func (x *Vote) GetYes() bool {
	if x != nil {
		return x.Yes
	}
	return false
}

type Decision struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Txn           uint64                 `protobuf:"varint,1,opt,name=txn,proto3" json:"txn,omitempty"`
	Commit        bool                   `protobuf:"varint,2,opt,name=commit,proto3" json:"commit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Decision) Reset() {
	*x = Decision{}
	mi := &file_proto_txn_v1_txn_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Decision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Decision) ProtoMessage() {}

func (x *Decision) ProtoReflect() protoreflect.Message {
	mi := &file_proto_txn_v1_txn_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Decision.ProtoReflect.Descriptor instead.
func (*Decision) Descriptor() ([]byte, []int) {
	return file_proto_txn_v1_txn_proto_rawDescGZIP(), []int{4}
}

func (x *Decision) GetTxn() uint64 {
	if x != nil {
		return x.Txn
	}
	return 0
}

func (x *Decision) GetCommit() bool {
	if x != nil {
		return x.Commit
	}
	return false
}

type QueryOutcome struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Txn           uint64                 `protobuf:"varint,1,opt,name=txn,proto3" json:"txn,omitempty"`
	From          uint32                 `protobuf:"varint,2,opt,name=from,proto3" json:"from,omitempty"`
	Participants  []uint32               `protobuf:"varint,3,rep,packed,name=participants,proto3" json:"participants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryOutcome) Reset() {
	*x = QueryOutcome{}
	mi := &file_proto_txn_v1_txn_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryOutcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryOutcome) ProtoMessage() {}

func (x *QueryOutcome) ProtoReflect() protoreflect.Message {
	mi := &file_proto_txn_v1_txn_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryOutcome.ProtoReflect.Descriptor instead.
func (*QueryOutcome) Descriptor() ([]byte, []int) {
	return file_proto_txn_v1_txn_proto_rawDescGZIP(), []int{5}
}

func (x *QueryOutcome) GetTxn() uint64 {
	if x != nil {
		return x.Txn
	}
	return 0
}

func (x *QueryOutcome) GetFrom() uint32 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *QueryOutcome) GetParticipants() []uint32 {
	if x != nil {
		return x.Participants
	}
	return nil
}

type WoundReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Txn           uint64                 `protobuf:"varint,1,opt,name=txn,proto3" json:"txn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WoundReq) Reset() {
	*x = WoundReq{}
	mi := &file_proto_txn_v1_txn_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WoundReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WoundReq) ProtoMessage() {}

func (x *WoundReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_txn_v1_txn_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WoundReq.ProtoReflect.Descriptor instead.
func (*WoundReq) Descriptor() ([]byte, []int) {
	return file_proto_txn_v1_txn_proto_rawDescGZIP(), []int{6}
}

func (x *WoundReq) GetTxn() uint64 {
	if x != nil {
		return x.Txn
	}
	return 0
}

// LeaderHint names a shard's leader as far as the answering node knows
// (id 0 and an empty addr if it knows of none).
type LeaderHint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaderHint) Reset() {
	*x = LeaderHint{}
	mi := &file_proto_txn_v1_txn_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaderHint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderHint) ProtoMessage() {}

func (x *LeaderHint) ProtoReflect() protoreflect.Message {
	mi := &file_proto_txn_v1_txn_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderHint.ProtoReflect.Descriptor instead.
func (*LeaderHint) Descriptor() ([]byte, []int) {
	return file_proto_txn_v1_txn_proto_rawDescGZIP(), []int{7}
}

func (x *LeaderHint) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LeaderHint) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

// Begin starts a transaction attempt. Any node answers.
type BeginRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Non-zero keeps the start timestamp of an earlier, aborted attempt, so
	// a retried transaction ages and eventually wins under wound-wait.
	Ts            uint64 `protobuf:"varint,1,opt,name=ts,proto3" json:"ts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeginRequest) Reset() {
	*x = BeginRequest{}
	mi := &file_proto_txn_v1_txn_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginRequest) ProtoMessage() {}

func (x *BeginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_txn_v1_txn_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeginRequest.ProtoReflect.Descriptor instead.
func (*BeginRequest) Descriptor() ([]byte, []int) {
	return file_proto_txn_v1_txn_proto_rawDescGZIP(), []int{8}
}

func (x *BeginRequest) GetTs() uint64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

type BeginResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Txn   *TxnMeta               `protobuf:"bytes,1,opt,name=txn,proto3" json:"txn,omitempty"`
	// Number of shards; keys map to shards by FNV-1a hash modulo this.
	Shards        uint32 `protobuf:"varint,2,opt,name=shards,proto3" json:"shards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeginResponse) Reset() {
	*x = BeginResponse{}
	mi := &file_proto_txn_v1_txn_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginResponse) ProtoMessage() {}

func (x *BeginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_txn_v1_txn_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeginResponse.ProtoReflect.Descriptor instead.
func (*BeginResponse) Descriptor() ([]byte, []int) {
	return file_proto_txn_v1_txn_proto_rawDescGZIP(), []int{9}
}

func (x *BeginResponse) GetTxn() *TxnMeta {
	if x != nil {
		return x.Txn
	}
	return nil
}

func (x *BeginResponse) GetShards() uint32 {
	if x != nil {
		return x.Shards
	}
	return 0
}

// Read goes to the leader of the key's shard. It takes a shared lock and
// returns the committed value and its version.
type ReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Txn           *TxnMeta               `protobuf:"bytes,1,opt,name=txn,proto3" json:"txn,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadRequest) Reset() {
	*x = ReadRequest{}
	mi := &file_proto_txn_v1_txn_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRequest) ProtoMessage() {}

func (x *ReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_txn_v1_txn_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRequest.ProtoReflect.Descriptor instead.
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return file_proto_txn_v1_txn_proto_rawDescGZIP(), []int{10}
}

func (x *ReadRequest) GetTxn() *TxnMeta {
	if x != nil {
		return x.Txn
	}
	return nil
}

func (x *ReadRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type ReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        Status                 `protobuf:"varint,1,opt,name=status,proto3,enum=txn.v1.Status" json:"status,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Version       uint64                 `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	Leader        *LeaderHint            `protobuf:"bytes,4,opt,name=leader,proto3" json:"leader,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadResponse) Reset() {
	*x = ReadResponse{}
	mi := &file_proto_txn_v1_txn_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadResponse) ProtoMessage() {}

func (x *ReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_txn_v1_txn_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadResponse.ProtoReflect.Descriptor instead.
func (*ReadResponse) Descriptor() ([]byte, []int) {
	return file_proto_txn_v1_txn_proto_rawDescGZIP(), []int{11}
}

func (x *ReadResponse) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

func (x *ReadResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *ReadResponse) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ReadResponse) GetLeader() *LeaderHint {
	if x != nil {
		return x.Leader
	}
	return nil
}

// Write goes to the leader of the key's shard before commit. It renews
// the transaction's locks there and fails fast if the transaction is
// already doomed. The value is buffered by the client and sent in Commit;
// write locks are taken at prepare.
type WriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Txn           *TxnMeta               `protobuf:"bytes,1,opt,name=txn,proto3" json:"txn,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteRequest) Reset() {
	*x = WriteRequest{}
	mi := &file_proto_txn_v1_txn_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteRequest) ProtoMessage() {}

func (x *WriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_txn_v1_txn_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteRequest.ProtoReflect.Descriptor instead.
func (*WriteRequest) Descriptor() ([]byte, []int) {
	return file_proto_txn_v1_txn_proto_rawDescGZIP(), []int{12}
}

func (x *WriteRequest) GetTxn() *TxnMeta {
	if x != nil {
		return x.Txn
	}
	return nil
}

func (x *WriteRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type WriteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        Status                 `protobuf:"varint,1,opt,name=status,proto3,enum=txn.v1.Status" json:"status,omitempty"`
	Leader        *LeaderHint            `protobuf:"bytes,2,opt,name=leader,proto3" json:"leader,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteResponse) Reset() {
	*x = WriteResponse{}
	mi := &file_proto_txn_v1_txn_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteResponse) ProtoMessage() {}

func (x *WriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_txn_v1_txn_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteResponse.ProtoReflect.Descriptor instead.
func (*WriteResponse) Descriptor() ([]byte, []int) {
	return file_proto_txn_v1_txn_proto_rawDescGZIP(), []int{13}
}

func (x *WriteResponse) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

func (x *WriteResponse) GetLeader() *LeaderHint {
	if x != nil {
		return x.Leader
	}
	return nil
}

// Commit goes to the leader of the coordinator shard, the lowest shard in
// parts. One part commits in one phase; more use two-phase commit. Commit
// is idempotent per txn id: after a timeout or a lost connection the
// outcome is unknown and the client retries the same request.
type CommitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Txn           *TxnMeta               `protobuf:"bytes,1,opt,name=txn,proto3" json:"txn,omitempty"`
	Parts         []*Part                `protobuf:"bytes,2,rep,name=parts,proto3" json:"parts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitRequest) Reset() {
	*x = CommitRequest{}
	mi := &file_proto_txn_v1_txn_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitRequest) ProtoMessage() {}

func (x *CommitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_txn_v1_txn_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitRequest.ProtoReflect.Descriptor instead.
func (*CommitRequest) Descriptor() ([]byte, []int) {
	return file_proto_txn_v1_txn_proto_rawDescGZIP(), []int{14}
}

func (x *CommitRequest) GetTxn() *TxnMeta {
	if x != nil {
		return x.Txn
	}
	return nil
}

func (x *CommitRequest) GetParts() []*Part {
	if x != nil {
		return x.Parts
	}
	return nil
}

type CommitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        Status                 `protobuf:"varint,1,opt,name=status,proto3,enum=txn.v1.Status" json:"status,omitempty"`
	Leader        *LeaderHint            `protobuf:"bytes,2,opt,name=leader,proto3" json:"leader,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitResponse) Reset() {
	*x = CommitResponse{}
	mi := &file_proto_txn_v1_txn_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitResponse) ProtoMessage() {}

func (x *CommitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_txn_v1_txn_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitResponse.ProtoReflect.Descriptor instead.
func (*CommitResponse) Descriptor() ([]byte, []int) {
	return file_proto_txn_v1_txn_proto_rawDescGZIP(), []int{15}
}

func (x *CommitResponse) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

func (x *CommitResponse) GetLeader() *LeaderHint {
	if x != nil {
		return x.Leader
	}
	return nil
}

// Abort releases the transaction's shared locks at one shard's leader.
// It is a hint: abandoned locks also expire.
type AbortRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Txn           uint64                 `protobuf:"varint,1,opt,name=txn,proto3" json:"txn,omitempty"`
	Shard         uint32                 `protobuf:"varint,2,opt,name=shard,proto3" json:"shard,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbortRequest) Reset() {
	*x = AbortRequest{}
	mi := &file_proto_txn_v1_txn_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbortRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbortRequest) ProtoMessage() {}

func (x *AbortRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_txn_v1_txn_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbortRequest.ProtoReflect.Descriptor instead.
func (*AbortRequest) Descriptor() ([]byte, []int) {
	return file_proto_txn_v1_txn_proto_rawDescGZIP(), []int{16}
}

func (x *AbortRequest) GetTxn() uint64 {
	if x != nil {
		return x.Txn
	}
	return 0
}

func (x *AbortRequest) GetShard() uint32 {
	if x != nil {
		return x.Shard
	}
	return 0
}

type AbortResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        Status                 `protobuf:"varint,1,opt,name=status,proto3,enum=txn.v1.Status" json:"status,omitempty"`
	Leader        *LeaderHint            `protobuf:"bytes,2,opt,name=leader,proto3" json:"leader,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbortResponse) Reset() {
	*x = AbortResponse{}
	mi := &file_proto_txn_v1_txn_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbortResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbortResponse) ProtoMessage() {}

func (x *AbortResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_txn_v1_txn_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbortResponse.ProtoReflect.Descriptor instead.
func (*AbortResponse) Descriptor() ([]byte, []int) {
	return file_proto_txn_v1_txn_proto_rawDescGZIP(), []int{17}
}

func (x *AbortResponse) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

func (x *AbortResponse) GetLeader() *LeaderHint {
	if x != nil {
		return x.Leader
	}
	return nil
}

var File_proto_txn_v1_txn_proto protoreflect.FileDescriptor

const file_proto_txn_v1_txn_proto_rawDesc = "" +
	"\n" +
	"\x16proto/txn/v1/txn.proto\x12\x06txn.v1\")\n" +
	"\aTxnMeta\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x0e\n" +
	"\x02ts\x18\x02 \x01(\x04R\x02ts\"\xf2\x01\n" +
	"\x04Part\x12\x14\n" +
	"\x05shard\x18\x01 \x01(\rR\x05shard\x12-\n" +
	"\x05reads\x18\x02 \x03(\v2\x17.txn.v1.Part.ReadsEntryR\x05reads\x120\n" +
	"\x06writes\x18\x03 \x03(\v2\x18.txn.v1.Part.WritesEntryR\x06writes\x1a8\n" +
	"\n" +
	"ReadsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01\x1a9\n" +
	"\vWritesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8b\x01\n" +
	"\n" +
	"PrepareReq\x12!\n" +
	"\x03txn\x18\x01 \x01(\v2\x0f.txn.v1.TxnMetaR\x03txn\x12\x14\n" +
	"\x05coord\x18\x02 \x01(\rR\x05coord\x12\"\n" +
	"\fparticipants\x18\x03 \x03(\rR\fparticipants\x12 \n" +
	"\x04part\x18\x04 \x01(\v2\f.txn.v1.PartR\x04part\"@\n" +
	"\x04Vote\x12\x10\n" +
	"\x03txn\x18\x01 \x01(\x04R\x03txn\x12\x14\n" +
	"\x05shard\x18\x02 \x01(\rR\x05shard\x12\x10\n" +
	"\x03yes\x18\x03 \x01(\bR\x03yes\"4\n" +
	"\bDecision\x12\x10\n" +
	"\x03txn\x18\x01 \x01(\x04R\x03txn\x12\x16\n" +
	"\x06commit\x18\x02 \x01(\bR\x06commit\"X\n" +
	"\fQueryOutcome\x12\x10\n" +
	"\x03txn\x18\x01 \x01(\x04R\x03txn\x12\x12\n" +
	"\x04from\x18\x02 \x01(\rR\x04from\x12\"\n" +
	"\fparticipants\x18\x03 \x03(\rR\fparticipants\"\x1c\n" +
	"\bWoundReq\x12\x10\n" +
	"\x03txn\x18\x01 \x01(\x04R\x03txn\"0\n" +
	"\n" +
	"LeaderHint\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\"\x1e\n" +
	"\fBeginRequest\x12\x0e\n" +
	"\x02ts\x18\x01 \x01(\x04R\x02ts\"J\n" +
	"\rBeginResponse\x12!\n" +
	"\x03txn\x18\x01 \x01(\v2\x0f.txn.v1.TxnMetaR\x03txn\x12\x16\n" +
	"\x06shards\x18\x02 \x01(\rR\x06shards\"B\n" +
	"\vReadRequest\x12!\n" +
	"\x03txn\x18\x01 \x01(\v2\x0f.txn.v1.TxnMetaR\x03txn\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\"\x92\x01\n" +
	"\fReadResponse\x12&\n" +
	"\x06status\x18\x01 \x01(\x0e2\x0e.txn.v1.StatusR\x06status\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x04R\aversion\x12*\n" +
	"\x06leader\x18\x04 \x01(\v2\x12.txn.v1.LeaderHintR\x06leader\"C\n" +
	"\fWriteRequest\x12!\n" +
	"\x03txn\x18\x01 \x01(\v2\x0f.txn.v1.TxnMetaR\x03txn\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\"c\n" +
	"\rWriteResponse\x12&\n" +
	"\x06status\x18\x01 \x01(\x0e2\x0e.txn.v1.StatusR\x06status\x12*\n" +
	"\x06leader\x18\x02 \x01(\v2\x12.txn.v1.LeaderHintR\x06leader\"V\n" +
	"\rCommitRequest\x12!\n" +
	"\x03txn\x18\x01 \x01(\v2\x0f.txn.v1.TxnMetaR\x03txn\x12\"\n" +
	"\x05parts\x18\x02 \x03(\v2\f.txn.v1.PartR\x05parts\"d\n" +
	"\x0eCommitResponse\x12&\n" +
	"\x06status\x18\x01 \x01(\x0e2\x0e.txn.v1.StatusR\x06status\x12*\n" +
	"\x06leader\x18\x02 \x01(\v2\x12.txn.v1.LeaderHintR\x06leader\"6\n" +
	"\fAbortRequest\x12\x10\n" +
	"\x03txn\x18\x01 \x01(\x04R\x03txn\x12\x14\n" +
	"\x05shard\x18\x02 \x01(\rR\x05shard\"c\n" +
	"\rAbortResponse\x12&\n" +
	"\x06status\x18\x01 \x01(\x0e2\x0e.txn.v1.StatusR\x06status\x12*\n" +
	"\x06leader\x18\x02 \x01(\v2\x12.txn.v1.LeaderHintR\x06leader*Z\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tSTATUS_OK\x10\x01\x12\x12\n" +
	"\x0eSTATUS_ABORTED\x10\x02\x12\x15\n" +
	"\x11STATUS_NOT_LEADER\x10\x032\x93\x02\n" +
	"\x03Txn\x124\n" +
	"\x05Begin\x12\x14.txn.v1.BeginRequest\x1a\x15.txn.v1.BeginResponse\x121\n" +
	"\x04Read\x12\x13.txn.v1.ReadRequest\x1a\x14.txn.v1.ReadResponse\x124\n" +
	"\x05Write\x12\x14.txn.v1.WriteRequest\x1a\x15.txn.v1.WriteResponse\x127\n" +
	"\x06Commit\x12\x15.txn.v1.CommitRequest\x1a\x16.txn.v1.CommitResponse\x124\n" +
	"\x05Abort\x12\x14.txn.v1.AbortRequest\x1a\x15.txn.v1.AbortResponseB:Z8github.com/Shrutij516/paxos-txn-store/proto/txn/v1;txnv1b\x06proto3"

var (
	file_proto_txn_v1_txn_proto_rawDescOnce sync.Once
	file_proto_txn_v1_txn_proto_rawDescData []byte
)

func file_proto_txn_v1_txn_proto_rawDescGZIP() []byte {
	file_proto_txn_v1_txn_proto_rawDescOnce.Do(func() {
		file_proto_txn_v1_txn_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_txn_v1_txn_proto_rawDesc), len(file_proto_txn_v1_txn_proto_rawDesc)))
	})
	return file_proto_txn_v1_txn_proto_rawDescData
}

var file_proto_txn_v1_txn_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_txn_v1_txn_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_proto_txn_v1_txn_proto_goTypes = []any{
	(Status)(0),            // 0: txn.v1.Status
	(*TxnMeta)(nil),        // 1: txn.v1.TxnMeta
	(*Part)(nil),           // 2: txn.v1.Part
	(*PrepareReq)(nil),     // 3: txn.v1.PrepareReq
	(*Vote)(nil),           // 4: txn.v1.Vote
	(*Decision)(nil),       // 5: txn.v1.Decision
	(*QueryOutcome)(nil),   // 6: txn.v1.QueryOutcome
	(*WoundReq)(nil),       // 7: txn.v1.WoundReq
	(*LeaderHint)(nil),     // 8: txn.v1.LeaderHint
	(*BeginRequest)(nil),   // 9: txn.v1.BeginRequest
	(*BeginResponse)(nil),  // 10: txn.v1.BeginResponse
	(*ReadRequest)(nil),    // 11: txn.v1.ReadRequest
	(*ReadResponse)(nil),   // 12: txn.v1.ReadResponse
	(*WriteRequest)(nil),   // 13: txn.v1.WriteRequest
	(*WriteResponse)(nil),  // 14: txn.v1.WriteResponse
	(*CommitRequest)(nil),  // 15: txn.v1.CommitRequest
	(*CommitResponse)(nil), // 16: txn.v1.CommitResponse
	(*AbortRequest)(nil),   // 17: txn.v1.AbortRequest
	(*AbortResponse)(nil),  // 18: txn.v1.AbortResponse
	nil,                    // 19: txn.v1.Part.ReadsEntry
	nil,                    // 20: txn.v1.Part.WritesEntry
}
var file_proto_txn_v1_txn_proto_depIdxs = []int32{
	19, // 0: txn.v1.Part.reads:type_name -> txn.v1.Part.ReadsEntry
	20, // 1: txn.v1.Part.writes:type_name -> txn.v1.Part.WritesEntry
	1,  // 2: txn.v1.PrepareReq.txn:type_name -> txn.v1.TxnMeta
	2,  // 3: txn.v1.PrepareReq.part:type_name -> txn.v1.Part
	1,  // 4: txn.v1.BeginResponse.txn:type_name -> txn.v1.TxnMeta
	1,  // 5: txn.v1.ReadRequest.txn:type_name -> txn.v1.TxnMeta
	0,  // 6: txn.v1.ReadResponse.status:type_name -> txn.v1.Status
	8,  // 7: txn.v1.ReadResponse.leader:type_name -> txn.v1.LeaderHint
	1,  // 8: txn.v1.WriteRequest.txn:type_name -> txn.v1.TxnMeta
	0,  // 9: txn.v1.WriteResponse.status:type_name -> txn.v1.Status
	8,  // 10: txn.v1.WriteResponse.leader:type_name -> txn.v1.LeaderHint
	1,  // 11: txn.v1.CommitRequest.txn:type_name -> txn.v1.TxnMeta
	2,  // 12: txn.v1.CommitRequest.parts:type_name -> txn.v1.Part
	0,  // 13: txn.v1.CommitResponse.status:type_name -> txn.v1.Status
	8,  // 14: txn.v1.CommitResponse.leader:type_name -> txn.v1.LeaderHint
	0,  // 15: txn.v1.AbortResponse.status:type_name -> txn.v1.Status
	8,  // 16: txn.v1.AbortResponse.leader:type_name -> txn.v1.LeaderHint
	9,  // 17: txn.v1.Txn.Begin:input_type -> txn.v1.BeginRequest
	11, // 18: txn.v1.Txn.Read:input_type -> txn.v1.ReadRequest
	13, // 19: txn.v1.Txn.Write:input_type -> txn.v1.WriteRequest
	15, // 20: txn.v1.Txn.Commit:input_type -> txn.v1.CommitRequest
	17, // 21: txn.v1.Txn.Abort:input_type -> txn.v1.AbortRequest
	10, // 22: txn.v1.Txn.Begin:output_type -> txn.v1.BeginResponse
	12, // 23: txn.v1.Txn.Read:output_type -> txn.v1.ReadResponse
	14, // 24: txn.v1.Txn.Write:output_type -> txn.v1.WriteResponse
	16, // 25: txn.v1.Txn.Commit:output_type -> txn.v1.CommitResponse
	18, // 26: txn.v1.Txn.Abort:output_type -> txn.v1.AbortResponse
	22, // [22:27] is the sub-list for method output_type
	17, // [17:22] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_proto_txn_v1_txn_proto_init() }
func file_proto_txn_v1_txn_proto_init() {
	if File_proto_txn_v1_txn_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_txn_v1_txn_proto_rawDesc), len(file_proto_txn_v1_txn_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_txn_v1_txn_proto_goTypes,
		DependencyIndexes: file_proto_txn_v1_txn_proto_depIdxs,
		EnumInfos:         file_proto_txn_v1_txn_proto_enumTypes,
		MessageInfos:      file_proto_txn_v1_txn_proto_msgTypes,
	}.Build()
	File_proto_txn_v1_txn_proto = out.File
	file_proto_txn_v1_txn_proto_goTypes = nil
	file_proto_txn_v1_txn_proto_depIdxs = nil
}
